---
apiVersion: v1
kind: Namespace
metadata:
  name: dovns

---
apiVersion: apps/v1
kind: Deployment  
metadata: 
  name: dov-deploy
  namespace: dovns 
  labels:
    app: dov
    name: dov-deploy
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: dov 
      name: dov-po 
  template: 
    metadata:
      name: dov-po 
      labels:
        app: dov 
        name: dov-po 
    spec:
      containers: 
      - name: dov-container
        image: chukmunnlee/dov-bear:v4 
        imagePullPolicy: IfNotPresent
        env: # environment variables
        - name: INSTANCE_HASH 
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: dov-cm
        ports:
        - name: web-port 
          containerPort: 3000
        - name: metrics-port 
          containerPort: 3100
        livenessProbe:
          httpGet:
            path: /healthz 
            port: web-port
          periodSeconds: 30
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: 32m
            memory: 64Mi
          limits:
            cpu: 32m
            memory: 64Mi

--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: dov-svc 
  namespace: dovns 
  labels:
    app: dov
    name: dov-svc 
spec:
  type: ClusterIP
  selector:
    app: dov 
    name: dov-po
  ports:
  - name: svc-web-port 
    port: 5000
    targetPort: web-port
  - name: svc-metrics-port 
    port: 5100
    targetPort: metrics-port

---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata: 
  name: dov-ing 
  namespace: dovns
  labels:
    app: dov
    name: dov-ing 
spec:
  ingressClassName: nginx 
  rules:
  - host: dov-139.59.223.166.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dov-svc 
            port:
              name: svc-web-port

--- 
apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler 
metadata: 
  name: dov-hpa 
  namespace: dovns 
spec: 
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: dov-deploy
  metrics:
  - type: Resource 
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: 80
  - type: Resource 
    resource:
      name: memory 
      target:
        type: Utilization 
        averageUtilization: 80